"jobs":
  "publish":
    "runs-on":
    - "ubuntu-latest"
    "steps":
    - "name": "Check out repository code"
      "uses": "actions/checkout@v2"
    - "env":
        "NPM_TOKEN": "${{ secrets.npm_token }}"
      "name": "npm"
      "run": "bash ./ci/npm.sh"
    - "name": "yarn"
      "run": "yarn --frozen-lockfile || yarn --frozen-lockfile"
    - "name": "build"
      "run": "yarn build"
    - "name": "publish"
      "run": "bash ./ci/publish.sh"
    "timeout-minutes": 30
"name": "publish-tag"
"on":
  "push":
    "tags": "*"